### Running simulations in python!
    Process
    Represent the data
    Create a matrix of random numbers to show simulations
    Determine the result of each simulation
    Get our experimental probability based on the results
## What's the probability of rolling a 2 on a 6-sided die?

In [3]:
import numpy as np
import pandas as pd

In [2]:
# define possible dice outcomes
outcomes = [1,2,3,4,5,6]

# define number of simulations
n_simulations = 10

In [3]:
#create matrix using our data for this problem
dice_rolls = np.random.choice(outcomes, n_simulations)
dice_rolls

array([6, 3, 4, 5, 4, 6, 3, 4, 4, 2])

In [4]:
dice_rolls == 2

array([False, False, False, False, False, False, False, False, False,
        True])

In [5]:
#count all the rolls that equal to 2
(dice_rolls == 2).sum()

1

In [6]:
#total number of Trues diveded by total rolls
(dice_rolls == 2).sum() / len(dice_rolls)

0.1

In [7]:
# define possible dice outcomes
outcomes = [1,2,3,4,5,6]

# define number of simulations
n_simulations = 100_000

#create matrix using our data for this problem
dice_rolls = np.random.choice(outcomes, n_simulations)
print(dice_rolls)

#take the average of boolean array 
(dice_rolls == 2).mean()

[6 3 4 ... 4 3 4]


0.16732

### How likely is it that you roll doubles when rolling two dice?

In [6]:
#outcomes
outcomes = [1,2,3,4,5,6]

#simulations & trials
n_trials = 2 #two dice
n_simulations = 100_000 #how many times we're rolling the dice

In [7]:
#set up number of simulations and number of dice rolls
two_dice_rolls = np.random.choice(outcomes, (n_simulations, n_trials))
two_dice_rolls

array([[6, 1],
       [6, 2],
       [6, 1],
       ...,
       [2, 3],
       [3, 5],
       [2, 1]])

In [8]:
two_dice_rolls.shape

(100000, 2)

    we have 100000 simulations, so we have 100000 rows
    we have 2 dice rolls per simulation, so we have 2 columns in each row

In [9]:
two_dice_rolls

array([[6, 1],
       [6, 2],
       [6, 1],
       ...,
       [2, 3],
       [3, 5],
       [2, 1]])

In [17]:
(two_dice_rolls == (2,2))

array([[False, False],
       [False,  True],
       [False, False],
       ...,
       [ True, False],
       [False, False],
       [ True, False]])

In [18]:
#be sure to sum across each simulation aka across each row (axis=1)
roll_counts = (two_dice_rolls == (2,2)).sum(axis=1)
roll_counts

array([0, 1, 0, ..., 1, 0, 1])

    this 1-d array shows how many rolls appeared in each simulations
    we want to know how many times we have 2 or more rolls, so lets convert that to a boolean array when our roll count is 2.

In [23]:
roll_counts == 2

array([False, False, False, ..., False, False, False])

In [24]:
(roll_counts == 2).mean()

0.02789

In [27]:
# define possible dice outcomes
outcomes = [1,2,3,4,5,6]

# define number of simulations
n_trials = 2 #two dice
n_simulations = 100_000

#create matrix using our data for this problem
dice_rolls = np.random.choice(outcomes, (n_simulations, n_trials))
# print(dice_rolls)
dice_rolls


array([[4, 1],
       [5, 6],
       [5, 4],
       ...,
       [1, 4],
       [1, 5],
       [4, 6]])

In [34]:
#take the average of boolean array 
dice_rolls = (0)
dice_rolls

SyntaxError: invalid syntax (2447421266.py, line 2)

In [ ]:
dice_rolls(2:)